# Generated by Django 3.2.7 on 2021-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('employee', 'schedule_date'), name='unique_shift'),
        ),
    ]
