# Generated by Django 3.2.7 on 2021-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_unique_shift'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_shift',
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('employee', 'schedule_date', 'title'), name='unique_shift'),
        ),
    ]
