# Generated by Django 3.2.7 on 2021-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0012_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='auth.Group'),
        ),
    ]
