# Generated by Django 3.2.7 on 2021-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultprofilepic.jfif', null=True, upload_to=''),
        ),
    ]
