# Generated by Django 3.2.7 on 2021-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
