# Generated by Django 3.2.7 on 2021-10-08 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20211004_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
