# Generated by Django 3.2.7 on 2021-10-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211008_0136'),
        ('userprofile', '0002_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='tasks',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.employee'),
        ),
    ]
