# Generated by Django 3.2.7 on 2021-10-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20211011_2202'),
        ('userprofile', '0004_remove_manager_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
