# Generated by Django 3.2.7 on 2021-10-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_delete_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=75, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telephone Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=2, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(max_length=200, null=True, verbose_name='Street Address'),
        ),
    ]
